# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'TipCalculator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TipCalculator
	pod 'GradientLoadingBar', '~> 2.0'

end
